<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_XmlPersistentEventStorage" Id="{b6d466bf-6b6d-4c4d-a0a8-da7bfd6efc42}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_XmlPersistentEventStorage IMPLEMENTS I_PersistentEventStorage
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="StoreEvent" Id="{44e4155d-7bf2-4577-b19d-81c1e94a07f5}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD StoreEvent
VAR_INPUT
	stEvent	: ST_Event;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_XmlPersistentEventStorage">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_XmlPersistentEventStorage.StoreEvent">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>